### ISSUE TITLE
Description field support for Option object

### ISSUE THREAD

**Issue by ddnomad** [oneor0/blockkit-slack#8]
https://github.com/oneor0/blockkit-slack/blob/master/blockkit/objects.py#L55-L61 

`blockkit.objects.Option` does not support `description` field as per Slack Block Kit [documentation](https://api.slack.com/reference/block-kit/composition-objects#option).

I'll try to create a PR shortly, a fix should not be too complicated (like 2 changed lines + tests iirc) unless @oneor0 has any objections :)

**Comment by oneor0** [comment]
Hey! Thank you for the fix. Your changes are available in version `0.6.0`
